import { Course, Suggestion } from './types';

export const recentlyVisitedCourses: Course[] = [
  {
    id: 1,
    title: 'Using Python',
    enrollments: 159452,
    session: 'Session 1',
    sessionDate: 'May 3, 2021 - present',
    status: 'Live',
    associatedWith: 'Google AI Essentials',
  },
  {
    id: 2,
    title: 'Use AI Responsibly',
    enrollments: 89452,
    session: 'Session 1',
    sessionDate: 'May 3, 2021 - present',
    status: 'Live',
    associatedWith: 'Masters of Science',
  },
];

export const allCourses: Course[] = [
  {
    id: 3,
    title: 'Popular Agile frameworks',
    enrollments: 89452,
    session: 'Session 1',
    sessionDate: 'May 3, 2021 - present',
    status: 'Live',
    associatedWith: 'Masters of Science',
  },
  {
    id: 4,
    title: 'Introduction to Git and Github',
    enrollments: 89452,
    session: 'Session 1',
    sessionDate: 'May 3, 2021 - present',
    status: 'Live',
    associatedWith: 'Masters of Science',
  },
  {
    id: 5,
    title: 'Use AI as a creative partner',
    enrollments: 89452,
    session: 'Session 1',
    sessionDate: 'May 3, 2021 - present',
    status: 'Live',
    associatedWith: 'Masters of Science',
  },
  {
    id: 6,
    title: 'Hello, Python!',
    enrollments: 89452,
    session: 'Session 1',
    sessionDate: 'May 3, 2021 - present',
    status: 'Live',
    associatedWith: 'Google AI Essentials',
  },
];

export const filteredCourses: Course[] = [
  {
    id: 7,
    title: 'Foundation of Data Science',
    enrollments: 89452,
    session: 'Session 1',
    sessionDate: 'May 3, 2021 - present',
    status: 'Live',
    associatedWith: 'Google AI Essentials',
    engagement: 68,
    completion: 72,
    potentialLift: 15,
    engagementTrend: 2,
  },
  {
    id: 8,
    title: 'Discover the art of prompting',
    enrollments: 89452,
    session: 'Session 1',
    sessionDate: 'May 3, 2021 - present',
    status: 'Live',
    associatedWith: 'Masters of Science',
    engagement: 55,
    completion: 60,
    potentialLift: 25,
    engagementTrend: -3,
  },
  {
    id: 9,
    title: 'Maximize productivity with AI',
    enrollments: 89452,
    session: 'Session 1',
    sessionDate: 'May 3, 2021 - present',
    status: 'Live',
    associatedWith: 'Google AI Essentials',
    engagement: 75,
    completion: 80,
    potentialLift: 10,
    engagementTrend: 0,
  },
    {
    id: 10,
    title: 'Foundation of Data Science', // Using the same as ID 7 as the image only shows 3 unique courses
    enrollments: 89452,
    session: 'Session 1',
    sessionDate: 'May 3, 2021 - present',
    status: 'Live',
    associatedWith: 'Google AI Essentials',
    engagement: 68,
    completion: 72,
    potentialLift: 15,
    engagementTrend: 2,
  },
];

export const courseSuggestions: Suggestion[] = [
  {
    id: 1,
    moduleNumber: 2,
    type: 'Dialogue',
    title: 'Peer Discussion on Module 2 Concepts',
    learningObjective: 'LO 1.3 – Describe key concepts in data science',
    engagementLift: 5,
    qualityScore: 85,
    rationale: 'Added based on engagement drop at 45% of Module 2.',
    rationaleTooltip: 'Engagement curve shows a 45% drop between sections 2.2 and 2.3. Similar courses that added Dialogues saw a +5% retention increase.',
    modelConfidence: 0.88,
    status: 'pending',
    defaultOpen: true,
  },
  {
    id: 2,
    moduleNumber: 3,
    type: 'Role Play',
    title: 'Applied Practice Scenario',
    learningObjective: 'LO 2.1 – Apply data analysis techniques',
    engagementLift: 7,
    qualityScore: 82,
    rationale: 'Added based on evidence of missing applied practice.',
    rationaleTooltip: 'Low scores on "applied learning" survey questions and 72% of learners skip optional practice quizzes. Adding role-play scenarios increased skill ratings by 8% in similar courses.',
    modelConfidence: 0.81,
    status: 'pending',
  },
  {
    id: 3,
    moduleNumber: 4,
    type: 'Tools-based Lab',
    title: 'Interactive Skill Lab',
    learningObjective: 'LO 4.2 – Utilize data workflow tools effectively',
    engagementLift: 6,
    qualityScore: 90,
    rationale: 'Added to reinforce skill demo.',
    rationaleTooltip: 'The "Skill Demo" video has a 60% replay rate, indicating confusion. Labs improve self-reported skill confidence by over 15%.',
    modelConfidence: 0.92,
    status: 'pending',
  },
];
